CREATE TABLE STORE_CUSTOMER(
     CUSTOMER_NO  NUMBER(4) PRIMARY KEY,
     FIRST_NAME VARCHAR2(20) NOT NULL,
     LAST_NAME VARCHAR2(20) NOT NULL,
     CITY VARCHAR2(20)
);

CREATE TABLE CUSTOMER_PHONE(
     CUSTOMER_NO NUMBER(4),
     PHONE_NO VARCHAR2(15),
     CONSTRAINT pk_customer_phone PRIMARY KEY (CUSTOMER_NO,PHONE_NO)
);

ALTER TABLE CUSTOMER_PHONE
     ADD CONSTRAINT customerphone_fk1 FOREIGN KEY(CUSTOMER_NO)
     REFERENCES STORE_CUSTOMER(CUSTOMER_NO);

CREATE TABLE BRAND(
     BRAND_NO NUMBER(4) PRIMARY KEY,
     BRAND_NAME VARCHAR2(20) NOT NULL,
     COUNTRY VARCHAR2(20),
     FOUNDED_YEAR NUMBER(4) CONSTRAINT foundedyer_min CHECK
(FOUNDED_YEAR>=1900)
);

CREATE TABLE PHONE_MODEL(
     PHONE_ID NUMBER(5) PRIMARY KEY,
     BRAND_NO NUMBER(4),
     MODEL_NAME VARCHAR2(30) NOT NULL,
     STORAGE_GB NUMBER(4) NOT NULL CONSTRAINT min_capacity CHECK
(STORAGE_GB>0),
     PRICE NUMBER(10,2) CONSTRAINT min_price CHECK (PRICE>0),
     CONSTRAINT phone_brand_fk1 FOREIGN KEY(BRAND_NO) REFERENCES
BRAND(BRAND_NO)
);

select * from tab;

CREATE TABLE PURCHASE(
     PURCHASE_ID NUMBER(5) PRIMARY KEY,
     CUSTOMER_NO NUMBER(4) NOT NULL,
     PHONE_ID NUMBER(5)   NOT NULL,
     PURCHASE_DATE DATE DEFAULT sysdate,
     QUANTITY NUMBER(2) NOT NULL,
     AMOUNT NUMBER(10,2) NOT NULL,
     PAYMENT_METHOD VARCHAR2(15) NOT NULL,
     CONSTRAINT foreignkey_customerno FOREIGN KEY(CUSTOMER_NO)
     REFERENCES STORE_CUSTOMER(CUSTOMER_NO),
     CONSTRAINT foreignkey_phoneid FOREIGN KEY (PHONE_ID)
     REFERENCES PHONE_MODEL(PHONE_ID)
);

ALTER TABLE PURCHASE
    ADD CONSTRAINT payment_cons 
    CHECK(PAYMENT_METHOD='Credit Card' or PAYMENT_METHOD='Cash'
    or PAYMENT_METHOD='Bank Transfer');


select * from tab;

INSERT INTO STORE_CUSTOMER(CUSTOMER_NO,FIRST_NAME,LAST_NAME,CITY)
VALUES(1001,'Ahmet','Yilmaz','Ankara');

INSERT INTO CUSTOMER_PHONE
VALUES(1001,05321234567);

INSERT INTO BRAND
VALUES(1,'Samsung','South Korea','1938');

COMMIT;
